\RideSocial\Bundle\VehicleBundle\Entity\Make:
    type: entity
    table: vehicle_make
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        description:
            type: string
            nullable: true
        createdAt:
            type: date
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: date
            gedmo:
                timestampable:
                    on: update
        createdBy:
            type: string
            gedmo:
                blameable:
                    on: create
        updatedBy:
            type: string
            gedmo:
                blameable:
                    on: create
        slug:
            type: string
            gedmo:
                slug:
                    - name
    ManyToOne:
        parent:
            targetEntity: \RideSocial\Bundle\VehicleBundle\Entity\Make
            inversedBy: children
            joinColumn: 
                name: parent_id
                referencedColumnName: id
    OneToMany:
        models:
            targetEntity: \RideSocial\Bundle\VehicleBundle\Entity\Model
            mappedBy: make