\RideSocial\Bundle\VehicleBundle\Entity\Style:
    type: entity
    table: vehicle_style
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        description:
            type: string
            nullable: true
        abbreviation:
            type: string
            nullable: true
        createdAt:
            type: date
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: date
            gedmo:
                timestampable:
                    on: update
        createdBy:
            type: string
            gedmo:
                blameable:
                    on: create
        updatedBy:
            type: string
            gedmo:
                blameable:
                    on: update
        slug:
            type: string
            gedmo:
                slug:
                    - name
    ManyToOne:
        models:
            targetEntity: \RideSocial\Bundle\VehicleBundle\Entity\Model
            mappedBy: style